Take backups from snapshots

diff --git a/lxdbackup b/lxdbackup
--- a/lxdbackup
+++ b/lxdbackup
@@ -16,6 +16,7 @@ source "$(dirname "$0")"/functions/log.sh
 
 # global variables
 _lxc=$(command -v lxc)
+_snapshot=lxdbackup
 
 # Cleanup when exiting unclean
 trap "cleanup; echo 'Unclean exit'" INT SIGHUP SIGINT SIGTERM
@@ -57,12 +58,54 @@ if [[ $# != 0 ]] ; then
   exit 1
 fi
 
+#TODO check these restored functions
+# delete snapshot if it exists
+delete_snapshot() {
+  local container="$1"
+  local snapname="$2"
+  local snap="${container}/${snapname}"
+
+  log_debug "delete_snapshot ${container} ${snapname}"
+
+  # delete snapshot if it exists
+  if lxc info "${container}" | grep -q "^  ${snapname} "; then
+    log_info "Attempting to delete snapshot '${snap}'"
+    if ! ${_lxc} delete "${snap}" ; then
+      log_error "FAILED to delete snapshot ${snap}"
+      return 1
+    fi
+    log_info "Successfully deleted snapshot ${snap}"
+  fi
+  return 0
+}
+
+# Create snapshot making sure deleted first
+create_snapshot() {
+  local container="$1"
+  local snapname="$2"
+  local snap="${container}/${snapname}"
+
+  log_debug "create_snapshot ${container} ${snapname}"
+
+  delete_snapshot "${container}" "${snapname}" || return 1
+
+  log_info "Attempting to create snapshot '${snap}'"
+  if ! ${_lxc} snapshot "${snap}" ; then
+    log_error "FAILED to create snapshot ${snap}"
+    return 2
+  fi
+  log_info "Successfully created snapshot ${snap}"
+
+  return 0
+}
+
+
 # Copy container 
 copy_container() {
   local source="$1"
   local container="$2"
   local pool="$3"
-  local copy_args="--stateless --instance-only --config=boot.autostart=false --storage ${pool}"
+  local copy_args="--stateless --config=boot.autostart=false --storage ${pool}"
 
   log_info "Attempting to copy '${source}'"
 
@@ -130,8 +173,11 @@ for _remote in "${_remotes[@]}"; do
   for _container in "${_containers[@]}"; do
     log_info "Backing up container ${_container}"
 
-    copy_container "${_remote}:${_container}" "${_container}" "${_pool}" || continue
+    create_snapshot "${_remote}:${_container}" ${_snapshot} || continue
 
+    copy_container "${_remote}:${_container}/${_snapshot}" "${_container}-backup" "${_pool}" || continue
+
+    delete_snapshot "${_remote}:${_container}" "${_snapshot}" || continue
     _remote_count+=1
   done
 
