Change to single copy using --instance-only

diff --git a/lxdbackup b/lxdbackup
--- a/lxdbackup
+++ b/lxdbackup
@@ -1,18 +1,18 @@
 #!/usr/bin/env bash
-# lxdbackup
 #
+# lxdbackup
 # Backup up all remote lxd instances using lxc copy
-# First backup is ia copy from a snapshot then full copy --refresh
-
-# shellcheck source=/dev/null
-for function in "$(dirname "$0")"/functions/*.sh; do source "${function}"; done
+# Note: the backed-up copy is deleted before copy
 
 set -o nounset
 set -o errexit
 set -o pipefail
 
+# Logging functions
+# shellcheck source=/dev/null
+source "$(dirname "$0")"/functions/log.sh
+
 # global variables
-_snapshot=lxdbackup
 _lxc=$(command -v lxc)
 
 # Cleanup when exiting unclean
@@ -57,55 +57,29 @@ dryrun(){
   _lxc="echo DRYRUN:${_lxc}"
 }
 
-# delete snapshot if it exists
-delete_snapshot() {
-  local container="$1"
-  local snapname="$2"
-  local snap="${container}/${snapname}"
-
-  log_debug "delete_snapshot ${container} ${snapname}"
-
-  # delete snapshot if it exists
-  if lxc info "${container}" | grep -q "^  ${snapname} "; then
-    log_info "Attempting to delete snapshot '${snap}'"
-    if ! ${_lxc} delete "${snap}" ; then
-      log_error "FAILED to delete snapshot ${snap}"
-      return 1
-    fi
-    log_info "Successfully deleted snapshot ${snap}"
-  fi
-  return 0
-}
-
-# Create snapshot making sure deleted first
-create_snapshot() {
-  local container="$1"
-  local snapname="$2"
-  local snap="${container}/${snapname}"
-
-  log_debug "create_snapshot ${container} ${snapname}"
-
-  delete_snapshot "${container}" "${snapname}" || return 1
-
-  log_info "Attempting to create snapshot '${snap}'"
-  if ! ${_lxc} snapshot "${snap}" ; then
-    log_error "FAILED to create snapshot ${snap}"
-    return 2
-  fi
-  log_info "Successfully created snapshot ${snap}"
-
-  return 0
-}
-
 # Copy container 
 copy_container() {
   local source="$1"
   local container="$2"
   local pool="$3"
-  local refresh="$4"
-  local copy_args="--stateless --config=boot.autostart=false --storage ${pool} ${refresh}"
+  local copy_args="--stateless --instance-only --config=boot.autostart=false --storage ${pool}"
 
-  log_notice "Attempting to copy '${source}' ${refresh}"
+  log_notice "Attempting to copy '${source}'"
+
+  # Check if container exists on local.
+  # If it does then make an initial copy of the container from a snapshot
+  # This is because making a copy of a running container using criu doesn't work for some reason
+  if [[ -n $(lxc list "^${container}\$" -c n --format=csv) ]] ; then
+    log_debug "${container} exists on local:, delete before copy"
+
+    if ! ${_lxc} delete "${container}" ; then
+      log_error "FAILED to copy ${container}, ABORTING BACKUP"
+      return 1
+    else
+      log_debug "deleted copy ${container}"
+    fi
+  fi
+  
   log_debug "${_lxc} copy ${source} ${container} ${copy_args}"
 
   # shellcheck disable=SC2086
@@ -158,21 +132,7 @@ for _remote in "${_remotes[@]}"; do
   for _container in "${_containers[@]}"; do
     log_notice "Backing up container ${_container}"
 
-    # Check if container exists on local.
-    # If it does then make an initial copy of the container from a snapshot
-    # This is because making a copy of a running container using criu doesn't work for some reason
-    if [[ -z $(lxc list "^${_container}\$" -c n --format=csv) ]] ; then
-      log_debug "${_container} doesn't exist on local:, create snapshot"
-
-      create_snapshot "${_remote}:${_container}" ${_snapshot} || continue
-
-      # Note empty 4th argument
-      copy_container "${_remote}:${_container}/${_snapshot}" "${_container}" "${_pool}" "" || continue
-
-      delete_snapshot "${_remote}:${_container}" "${_snapshot}" || continue
-    fi
-  
-    copy_container "${_remote}:${_container}" "${_container}" "${_pool}" --refresh || continue
+    copy_container "${_remote}:${_container}" "${_container}" "${_pool}" || continue
 
     _remote_count+=1
   done
